### ISSUE TITLE
"should be installed with -g"

### ISSUE THREAD

**Issue by olsonpm** [ivanakimov/hashids.js#14]
I just ran "npm install hashids --save" and it warned I should be installing the library globally?

The home page explains how to use via a javascript api, and the only reason I'm aware to install an npm library globally is so that you have command line access.  Mind explaining this error in more detail?

Thanks

**Comment by ivanakimov** [comment]
Hi @olsonpm,

You're right, the `-g` parameter is not needed. There is no command line support for [Node.js version](https://github.com/ivanakimov/hashids.node.js) of this library, so I removed it from the README: https://github.com/ivanakimov/hashids.node.js/commit/daece06bc50f81de65c8648952ebb8896bcae032

**tl&dr:** the usual `npm install` in your project directory should install Hashids, if you have it included in your `package.json`

**Comment by olsonpm** [comment]
Awesome - I appreciate the prompt response.  I'm relatively new to front-end, hence my uncertainty with gotchas like these.

**Comment by ivanakimov** [comment]
Cool, no problem. Also, another minor thing probably worth mentioning:

There's 2 separate repos for [frontend js](https://github.com/ivanakimov/hashids.js) and [backend js](https://github.com/ivanakimov/hashids.node.js) - one is for `bower`, another is for `npm`. Same code, different repositories - I'll probably merge them into the same repo eventually.
