### ISSUE TITLE
Won't encode long integers on particular machines

### ISSUE THREAD

**Issue by bgold0** [ivanakimov/hashids.js#16]
I'm trying to use Hashid's on my PHP Google App Engine. For some reason when I try to encode the integer below, it doesn't work. I've even tried without a salt. However, it works on my local machine.

Are there any checks I can do to see if I am doing something wrong or to see if something is needed to support a long integer value?

**NOTE:** bcmath is enabled

    //doesn't work
    $hashids = new Hashids\Hashids('threehorn');
    echo $hashids->encode(5183105597964288);

    //works
    $hashids = new Hashids\Hashids('threehorn');
    echo $hashids->encode(518310559);

**Comment by ivanakimov** [comment]
This is the JS repository of Hashids, but anyway - you're probably going beyond the upper limit (the limit will depend on the machine). You can check it using `$hashids->get_max_int_value();` Read more about it here: https://github.com/ivanakimov/hashids.php#big-numbers

**Comment by bgold0** [comment]
Ah my bad, thanks for the help

**Comment by ivanakimov** [comment]
No problem.
