### ISSUE TITLE
Salt quality and Hash max length

### ISSUE THREAD

**Issue by newtonianb** [ivanakimov/hashids.js#18]
Two quick questions

1. What should I use for my salt, can I use any type of character and whats the recommended length?
2. I was planning to store this in the database, how many characters should I account for in worst case scenarios?

**Comment by tmorehouse** [comment]
The salt length is totally up to you (or whoever is hashing the values). The salt could be a single character, could be a million characters, could be no characters.

**Comment by miquelfire** [comment]
How are you generating the numbers to create the hash?

Unless you want to save the generated hashes in case something changes (like the salt or the algorithm), you may not need to store them in the first place.

**Comment by miquelfire** [comment]
BTW, if you will store them, figure out what the biggest number(s) you'll send to the encode function will be. if you're using x-bit numbers, look [here](http://en.wikipedia.org/wiki/Integer_%28computer_science%29#Common_integral_data_types)

Otherwise, however you're generating the numbers need to be used.

**Comment by newtonianb** [comment]
The numbers I'm hashing is actually a SQL ID for records. I use it all the time so I considered storing this in the database.

Would 32 characters recommended? I understand it's up to me but would like to know what you would use best trade off between performance / security.

Thanks for the prompt response :+1:

**Comment by tmorehouse** [comment]
Note that Hashids are not cryptographically secure. (they are just obfuscated values)

The length of the salt does not affect the length of the resultant hashid (it is just used to randomize the alphabet in use). The length of the hash ID is related to the number of values stored in the hashid, the size of the numbers stored, and the length of the alphabet used for encoding.

One test you can do is pick the largest number possible for each value that you may have, and generate a Hashid and measure the string length.  You can also use the min hash length parameter to increase this size.

One note about storing hashids in some databases is that the database field may be case-insensitive.  i.e. FooBar and FOObar and FoObAR are considered the same string.  Select a binary field type/coalition to make sure the field is case sensitive, or use an alphabet with only lower case character or only upper case characters.

**Comment by ivanakimov** [comment]
Hi @newtonianb, sorry for late response. Looks like the guys have already answered it all!

To reiterate on what @tmorehouse and @miquelfire have said:

1. The salt characters and length is up to you, honestly makes little difference what you use -- just be sure it's something unique to you / your project. As an example, here's one of the salts I use on my own project: `Sup3r--SecreT__s4lt`
2. Id length depends on the size and the number of integers you decide to encode into one id, so encode the largest number(s) and see what length you get. If you decide that 32 characters is enough, use that. I wouldn't worry about performance too much, if you decide to use 255 characters for that column, it'll hardly make a dent for your SQL database, performance-wise.

A quick example link regarding case-sensitivity that @tmorehouse is talking about: https://github.com/ivanakimov/hashids.php/issues/22
