### ISSUE TITLE
Custom Alphabet returns same result with different salts

### ISSUE THREAD

**Issue by LRSutton** [ivanakimov/hashids.js#20]
Using hash-ids-js v1.0.2

The sample code provided:

	/* creating class object with custom alphabet */
	var hashids = new Hashids("this is my salt", 0, "abcdefgh123456789");

	/* encoding several numbers into one id */
	var id = hashids.encode(1, 2, 3, 4);

	/* decoding the same id */
	var numbers = hashids.decode(id);

	/* numbers is always an array */
	console.log(id, numbers);

returns: 16h4cba3 [1, 2, 3, 4]

Changing the salt to "this is not my salt" returns: 14h5cba3 [1, 2, 3, 4]
But changing the salt to "this is my other salt": 16h4cba3 [1, 2, 3, 4]  // Repeats original value

Expectation is that each salt / encode value would result in completely different values like it does when the custom alphabet is not specified. This is extremely simplified, I found the behavior using much more complex salt values.

**Comment by tmorehouse** [comment]
Different salts (but using same alphabet) may produce the same end results.  The salt is used to shuffle the alphabet in use. The resulting shuffle may end up being the same (or similar) to the result produced by other salts.

A good test would be to encode a larger range of ids, or a few ids with a larger integer value in your test above, and see fihte results differ.

**Comment by ivanakimov** [comment]
Hi @LRSutton,

To add to @tmorehouse's answer -- consistent shuffle function uses a slightly modified version of [Fisher–Yates](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) to shuffle alphabet. It's a good balance between speed and randomness, but results are not perfectly unique.

Salt was really meant to be used as a company name, or project title. If you try "salt1" vs "salt2", you definitely will not get the best shuffle as you've already discovered.

**Comment by LRSutton** [comment]
I've been using 7-digit integers as the basis for the original challenge
set.  The salts are 23-digit numbers.  And even over a series of sats the
same integer gets the same value every time.

- Lorin

**Comment by ivanakimov** [comment]
Closing. @LRSutton, sounds like this might be the wrong tool for your use-case. If you do decide to stick with it, you could experiment with substituting the consistent shuffle function with something that provides better results.
