### ISSUE TITLE
Is "minAlphabetLength = 16" required?

### ISSUE THREAD

**Issue by liukun** [ivanakimov/hashids.js#21]
I tried only use numbers as alphabet, and seems worked:
```coffeescript
coffee> hashids = new hashids "aaa", 9, "0123456789"
{ version: '0.3.3',
  minAlphabetLength: 2,
  sepDiv: 3.5,
  guardDiv: 12,
  errorAlphabetLength: 'error: alphabet must contain at least X unique characters',
  errorAlphabetSpace: 'error: alphabet cannot contain spaces',
  alphabet: '347895',
  seps: '012',
  minHashLength: 9,
  salt: 'aaa',
  guards: '6' }
coffee> hashids.encrypt 1
'547645689'
coffee> hashids.decrypt '547645689'
[ 1 ]
```
Are there some implicit requirements in algorithm?

**Comment by ivanakimov** [comment]
Looks like you're using a bit of an older version, where min length is 2. But for newer versions, check out these comments as to why 16 is minimum:
- https://github.com/ivanakimov/hashids.php/issues/29#issuecomment-65527260
- https://github.com/ivanakimov/hashids.js/issues/11#issuecomment-56536139

**Comment by liukun** [comment]
Thank you very much! So I can just use alphabet `"0123456789cfhistuCFHISTU"` to achieve my goal that only use `0123456789` as characters of the generated id when not need seperators.

```coffeescript
coffee> hashids = new (require 'hashids') "aaa", 9, "0123456789cfhistuCFHISTU"
{ version: '1.0.2',
  minAlphabetLength: 16,
  sepDiv: 3.5,
  guardDiv: 12,
  errorAlphabetLength: 'error: alphabet must contain at least X unique characters',
  errorAlphabetSpace: 'error: alphabet cannot contain spaces',
  alphabet: '602137945',
  seps: 'IcHFihUufCStsT',
  minHashLength: 9,
  salt: 'aaa',
  guards: '8' }
coffee> hashids.encode 1
'120805874'
coffee> hashids.encode 100000
'869749698'
coffee> hashids.decode '120805874'
[ 1 ]
```

**Comment by ivanakimov** [comment]
Yes. Also for your use-case, check out `#3` on this: http://hashids.org/#alternatives

**Comment by liukun** [comment]
@ivanakimov Great! Thanks for the info.
In my case, an user may need to input id by hand, so I think `hashids` is better because the generated string could have shorter length compared to Optimus'.

**Comment by godbout** [comment]
I'm using "0123456789cfhistuCFHISTU" too, and I only get numbers which is what I'm looking for, but I don't understand why 😂️

It is said that "the algorithm tries to avoid generating most common English curse words by never placing the following letters (and their uppercase equivalents) next to each other". So, how is it that those letters are not even found one time in the generated hashids? It could be put between 2 numbers, no?

**Comment by liukun** [comment]
@godbout IIRC those characters are used for separators when you encoding an array

**Comment by godbout** [comment]
@liukun yeah I saw that in the doc, but from what I understood from the doc and the source, those letters could still show up in the generated hashid. But like you, I just receive numbers, which I find very strange (although this is what I want, but I can't confirm that it would then work all the time?). I don't use Optimus neither because I want to control the length of the numbers generated.

**Comment by liukun** [comment]
@godbout Array separator

```
> hashids.encode(1)
'120805874'
> hashids.encode(2)
'347821860'
> hashids.encode([1,2]) # array
'24815c381'
> hashids.encode([1,2,3,4]) # array
'805c4H9F9'
```

**Comment by godbout** [comment]
🤦🏻‍♂️😂

Got it sorry. Holiday mood 😂 
Thanks a lot!
