### ISSUE TITLE
Migrating to a new salt?

### ISSUE THREAD

**Issue by olalonde** [ivanakimov/hashids.js#26]
I have the following problem. I have a PostgreSQL table with an auto incrementing ID on rows and use hashids to encode those IDs in URLs (let's say we have 1000 rows currently). However, I need to change the salt that we are using and was wondering how I might be able to do this without adding too much complexity.

One option would be to change the path prefix of URLs so that we can know which salt to use `/oldpath/:hashedid` (uses old salt) `/newpath/:hasedid` (uses new salt), that would probably be the most simple solution, but I have to chose a new path.

Another option would be to attempt to decode the hashed id with both salts:

1) Decode with the old salt. If the decoded integer is between 0-1000 (largest ID at the time we switched to the new salt), use that integer. 
2) Otherwise, decode with new salt.

The problem however is that there might be hash collisions :( (e.g. the new salt generates a hash from X that when decoded with the old salt produces an integer Y between 0-1000, which the decoding function would recognise as an old hash). 

I'm running out of imagination here and was wondering if anyone else had done this before and what strategy was used.

**Comment by ivanakimov** [comment]
Another way of distinguishing is by ID length. If you know that all of your current IDs are 5 characters, then your new ones can be length 6 and up (use the padding param in constructor).

If that's not ideal, I'd go with the path route: `/oldpath/v:hashedid`

**Comment by olalonde** [comment]
Ah yeah, that's not a bad idea, I guess I could increase size.
