### ISSUE TITLE
JavaScript version is different on websites:  v1.0.2  vs  v1.1.1

### ISSUE THREAD

**Issue by ucsdmath** [ivanakimov/hashids.js#30]
I noticed the versions are different between websites for the JavaScript.
I found the latest though for JavaScript:

- npm (1.1.1) : https://www.npmjs.com/package/hashids
- Github (1.1.1) : https://github.com/ivanakimov/hashids.js/releases
- website (1.0.2) : http://hashids.org/javascript/

Also, another idea:
I think it would be a great thing to coordinate the version numbers
for this code between all versions: PHP, Perl, Python, Ruby... v1.1.1

Just an idea. I am not sure if that is something that can be done or want,
but I wanted to suggest.  It is a great utility to me.  Thank you.

Daryl

**Comment by ivanakimov** [comment]
Updated, thanks 👍 

Re: versions, we're [somewhat] doing that already. Major version shows that ids are the same across implementations, minor differs, and patch always changes of course.
