### ISSUE TITLE
Feature Request:  Change Salt Key in current instance (on the fly)

### ISSUE THREAD

**Issue by ucsdmath** [ivanakimov/hashids.js#31]
Change on demand the Salt/Key would be cool not to create another Object:

```
var hashids = new Hashids('My Project');
console.log(hashids.encode(1, 2, 3)); // Z4UrtW

hashids.setSalt('My Other Project');
console.log(hashids.encode(1, 2, 3)); // gPUasb

console.log(hashids.getSalt()); // My Other Project
```
It would be nice both in PHP and JS.

Anyway,  thank you.

**Comment by ivanakimov** [comment]
Devs should handle that outside the library. It can be a source of bugs to figure out at what point the salt changed and why generated ids are now different / have collisions. Just create another object.
