### ISSUE TITLE
Problem with unsinged int 64

### ISSUE THREAD

**Issue by lester-s** [ivanakimov/hashids.js#33]
Hello,

I am trying to hash the max value of unsigned int64 (18446744073709551615). But if i try to hash the value just before (see exemple). it generates the same hash. Do you have any limit for the int value ? Its seems like it's rounded. Would it be possible to fix this ?

Thank you and have a nice day.

exemple:
var Hashids = require('hashids');
var hashids = new Hashids('', 40, 'ABCDEFGHIJKLMNPQRSTUVWXYZ23456789');
console.log('hash1:' + hashids.encode(18446744073709551615));
console.log('hash2:' + hashids.encode(18446744073709551614));

**Comment by ivanakimov** [comment]
You're way over [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). Break this number down into 2 and encode then.
