### ISSUE TITLE
TypeError: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by wellcaffeinated** [ivanakimov/hashids.js#34]
> TypeError: Cannot read property 'charCodeAt' of undefined
> 19:37:38 dev.1  |         at Hashids._encode (/node_modules/hashids/dist/hashids.js:251:45)
> 19:37:38 dev.1  |         at Hashids._decode (/node_modules/hashids/dist/hashids.js:312:15)
> 19:37:38 dev.1  |         at Hashids.decode (/node_modules/hashids/dist/hashids.js:184:17)

The hash happens to be "ypqyiyp", and contains one letter that isn't in the allowed character library. I'm not sure why I'm getting this error. It's just failing instead of returning null. Please advise

**Comment by ivanakimov** [comment]
Can you post a sample w/ constructor params? If salt is private, you can send me an email: ivan@barreleye.com

**Comment by wellcaffeinated** [comment]
I'll send you an email with the info.

**Comment by shushenghong** [comment]
same problem.

`
var userHashIds = new Hashids( "key-user", 5, 'abcdefghijklmnopqrstuvwxyz1234567890' ); 
var ids = userHashIds.decode( "as-buy7-kk" );
`

**Comment by ivanakimov** [comment]
Pushed `1.1.4`. Could you guys give it a shot?

**Comment by ivanakimov** [comment]
Closing. Re-open with constructor params + sample decode id, if issues.
