### ISSUE TITLE
question about guessing multiple valid hashids given one valid hashid

### ISSUE THREAD

**Issue by jaufgang** [ivanakimov/hashids.js#35]
I have noticed a pattern with hashids where if you have one hashid, you can easily find other hashids  by removing individual characters.

For example, with a particular salt i generate a hashid `jnmq4r`.  Using that hashid, if I remove characters from the string and try to decode those shorter strings, i get a valid number.

for example:

|hashid|decoded number|
|-|-|
|jnmq4r| 214003|
|jmq4r| 54003|
|jnq4r|14003|
|jnm4r| 10403|
|jnmqr|10703|
|jn4r|403|
|jq4r|6003|

This means that if a user is given a hashid, they can easily guess numerous other valid hashids.  It also means that if i want to do a quick check that a typed string is a valid hashid that can be mapped back to an integer using our salt, and there is a typo where a single letter is omitted, there is a very high probability that the error will not be detected.  

I get that hashids are not meant to be cryptograhically secure or strong, but I need something where given a set of valid codes it is still somewhat difficult go guess or generate additional valid codes.  

Is there any way I can still accomplish this with hashids, or do I need to go looking somewhere else?

**Comment by ivanakimov** [comment]
Correct.

It's the same with regular hex -- if you remove characters, you'll get valid numbers. The "salt" is there so that your `214003` differs from another project's `214003`, and so that its harder to guesstimate what the next number in the sequence (`214004`) will convert to.

Sounds like you need another lib.

**Comment by jaufgang** [comment]
Actually, I have been experimenting a bit and it seems like I can accomplish what I need by encoding multiple values into a single hashid.  if I `encode(214003,1)` instead of `encode(214003)` and remove single characters from the encoded hashid, those do not readily decode back to a valid pair of numbers.  Adding the second number seems to scramble the characters better.

I had tried `encode(214003, Date.now() %100)` but I don't even think that is necessary, simply adding a static 1 seems to work.

**Comment by tmorehouse** [comment]
When "guessing" the numbers, one would also need to know the `salt` used, (as well as the order of the `alphabet` used) when the numbers were encoded in order to properly decode the value.

If you are using the default `alphabet` and no `salt`, then the hasid can easily be decoded..

Hashids is an obfuscation library, not an encryption library.  Anyone with the cpu power of a pocket calculator could probably decode any hashid given enough samples.

**Comment by tmorehouse** [comment]
If you add a number in the front (i.e. a random number) and encode that random number and your regular sequential number, you will get more obfuscation., and less patterns will show.

**Comment by jaufgang** [comment]
I get that, and that's fine for my purposes.  I just don't want it to be trivially easy to stumble across another valid hashid by slightly varying a hashid that has been issued

**Comment by tmorehouse** [comment]
Entropy is your friend.

Encode two numbers to generate your hashids, with the first number being the entropy (and discardable, usually a random number),and the second number is your sequential value (i.e. primary key ID).  This will generate slinger hashids, but will make them appear more random. Taking the idea a step further would be to encode a 3rd number (random as well) at the end.  Ensure the random numbers vary in the number of digits they have as well (i.e. from 1 to 6 digits).

The only issue is if you re generating the IDs every time then you would need to store the entropy value alongside the sequential number so you can regenerate it.  But if you are storing the calculated hashid, then you wouldn't need to.

**Comment by jaufgang** [comment]
That's perfect.  Thank you  for your quick responses!
