### ISSUE TITLE
No default export in Node (immediately overwritten)

### ISSUE THREAD

**Issue by niieani** [ivanakimov/hashids.js#36]
Hi @ivanakimov.

The code generated [here](https://github.com/ivanakimov/hashids.js/blob/master/dist/hashids.js#L374-L375) is quite odd. It proceeds to set the default export as Hashids class, and immediately after overwrites the exports with the same, previously defined default export. The result is that there is no default export for ES6, but only a _root_ CommonJS export.

This will of course work if you use something like babel, which emits an interop between default (ES6) and root exports, but will not work if you consume the code directly, e.g. from Node or TypeScript.

A backwards compatible fix would be to add a 'default' property to the class, which points to itself.

**Comment by ivanakimov** [comment]
I'm using it in Node v8.1.0 and this works:
```javascript
const Hashids = require('hashids');
```

How are you using it?

**Comment by niieani** [comment]
Yes, that works, because CommonJS' `require` exposes the `module.exports`.

However, when used from within transpiled code that expects ES6 module APIs, it breaks:

```ts
import Hashids from 'hashids'
```

The above will only work if you use the [babel interop](https://gist.github.com/niieani/95b84d8999bab214a807c2c75380039b) that uses either the `default` export or `module.exports` fallback.

However, the original code for hashids [suggests a default export](https://github.com/ivanakimov/hashids.js/blob/master/lib/hashids.js#L2). According to the spec, this should transpile to:

```js
module.exports.default = Hashids;
```

The problem with the above however would be that it would break your current syntax:

```js
const Hashids = require('hashids');
```

i.e. a client would have to explicitly use:

```js
const Hashids = require('hashids').default;
```

There's a way to support both, though.

```js
module.exports = Object.assign(Hashids, {
  _esModule: true,
  default: HashIds,
})
```

The culprit seems to be with the choice of the babel plugin, the outdated `add-module-exports`.

Replacing with [`transform-es2015-modules-commonjs`](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs) would solve the problem, but would be a breaking change, since you'd need to do `require('hashids').default` from within NodeJS.

**Comment by MattiLehtinen** [comment]
I had no success with typescript because of this issue. Had to comment out the last line of the library to make it work without errors:

`// module.exports = exports['default'];`

```
import Hashids from "hashids";
const hashids = new Hashids("MySalt");
```

Without the modification I get an error:
`TypeError: hashids_1.default is not a constructor`

**Comment by cormacrelf** [comment]
In Typescript you can still use the `const Hashids = require('hashids');` form, in the meantime.

**Comment by niieani** [comment]
@cormacrelf only if you target Node. All other forms are broken:

https://codesandbox.io/s/932061k8jw

**Comment by cormacrelf** [comment]
@niieani I don’t target node. I use Webpack via `@angular/cli`. It handles `require` just fine, minus tree shaking, but this is a one-file module. Try it at the end of that code sandbox.

**Comment by niieani** [comment]
@cormacrelf yeah, either Node or if you use Webpack. CodeSandbox doesn't support requires in TypeScript though.

**Comment by anisabboud** [comment]
I encountered the same issue with Typescript / Angular.

Installed the library and typings via npm:

    npm install --save hashids
    npm install --save @types/hashids

Importing it as follows results in `ERROR TypeError: hashids_1.default is not a constructor`:

    import Hashids from 'hashids';
    const hashids = new Hashids('mysalt');

@cormacrelf's workaround worked for me:

    const Hashids = require('hashids');
    const hashids = new Hashids('mysalt');

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15920 might be related.

**Comment by mnasyrov** [comment]
My workaround in typescript:
```typescript
import Hashids, * as HashidsConstructor from 'hashids';
//...
const hashids: Hashids = new (HashidsConstructor as any)();
```

**Comment by gDelgado14** [comment]
Doesn't

```javascript
import * as Hashids from 'hashids'
```

Solve the issue?

**Comment by niieani** [comment]
@gDelgado14 no, because typings (and the code) defined a "default" export. Therefore the typings, which are 1:1 with the source code (but not 1:1 with the wrongly transpiled code) expose such a default export. With your code, constructor is available at `Hashids`, but the typings are exposed at `Hashids.default`.

**Comment by gDelgado14** [comment]
@niieani The following declaration file worked for me in my local project:

```
/// <reference types="node" />

declare module 'hashids' {
  class Hashids {
    private version: string;
    private minAlphabetLength: number;
    private sepDiv: number;
    private guardDiv: number;
    private errorAlphabetLength: string;
    private errorAlphabetSpace: string;
    private alphabet: string[];
    private seps: string;
    private minHashLength: number;
    private salt: string;
    constructor(salt: string, minHashLength?: number, alphabet?: string);
    public decode(hash: string): number[];
    public encode(arg: number): string;
    public encode(arg: number[]): string;
    public encode(...args: number[]): string;
    public encodeHex(str: string): string;
    public decodeHex(hash: string): string;
    public hash(input: number, alphabet: string): string;
    public unhash(input: string[], alphabet: string): number;
  }

  export = Hashids
}
```

**Comment by gDelgado14** [comment]
@niieani 

I think the proper declaration file might look something like that of redux-logger.

https://github.com/Microsoft/TypeScript/issues/5565#issuecomment-155216760

**Comment by niieani** [comment]
@gDelgado14 yes, changing the TypeScript declaration is one way of fixing the TypeScript issue. But it doesn't change the fact that the transpiled code is nonsensical, caused by the deprecated `add-module-exports` plugin:

https://github.com/ivanakimov/hashids.js/blob/d208f522ffdd2356655911b90274a625e2262c0a/dist/hashids.js#L374-L375

See my previous comment for a solution https://github.com/ivanakimov/hashids.js/issues/36#issuecomment-318149642.

**Comment by ivanakimov** [comment]
I could use some help with this. What's the best way to set this up without introducing breaking changes?

**Comment by niieani** [comment]
@ivanakimov I've fixed the issue in a backwards compatible way in #53.

**Comment by anisabboud** [comment]
Thank you Bazyli and Ivan!

The [CHANGELOG](https://github.com/ivanakimov/hashids.js/blob/master/CHANGELOG.md) mentions that v1.2.0 includes the fix, but seems like it hasn't been pushed to [npm](https://www.npmjs.com/package/hashids) yet.
