### ISSUE TITLE
Version Update v1.1.2 on Github / npm

### ISSUE THREAD

**Issue by ucsdmath** [ivanakimov/hashids.js#39]
Hi Ivan, npm shows an update to v1.1.2 for hashed.js.  In the changelog, I could not see what was updated from 1.1.1.  Also, Github does not show a patched version to v1.1.2.  Thank you.

**Comment by ivanakimov** [comment]
Hey @ucsdmath, I'm not sure why you're not able to see the CHANGELOG. It's here: <https://github.com/ivanakimov/hashids.js/blob/master/CHANGELOG.md> and also shows up properly for me in `hashids@1.1.2` upon install.

```
1.1.2:

- fixed issue with sourceMappingURL in hashids.min.js (PR #38)
- added package-lock.json
```

**Comment by ucsdmath** [comment]
Sorry, my mistake.  I went to https://github.com/ivanakimov/hashids.js/releases and clicked on the latest release v1.1.1   I was reading that log, but I downloaded the latest from npm (and not reading that log file).  My bad!  Thank you.
