### ISSUE TITLE
Unknown plugin add-module-exports specified in ./babelrc

### ISSUE THREAD

**Issue by yummyelin** [ivanakimov/hashids.js#40]
Trying to use hashids on react native app, but got error.

TransformError:  ../node_modules/hashids/dist/hashids.js: Unknown plugin "add-modules-exports" specified in "../node_modules/hashids/./babelrc" at 0, attempted to resolve relative to "../node_modules/hashids"

```
"hashids": "^1.1.2",
"react": "16.0.0-alpha.12",
"react-native": "^0.49.3",
```

Thanks!

**Comment by yummyelin** [comment]
Solved by run `npm install` in `../node_modules/hashids`

**Comment by nicolasdanelon** [comment]
is this fixed in the latest release?
