### ISSUE TITLE
Idea: accepting UUIDs as input

### ISSUE THREAD

**Issue by hi2u** [ivanakimov/hashids.js#41]
# UUID input

UUIDs are becoming more and more common as primary keys.  I was thinking it would be great if along with integers, the hashids library could take UUIDs as input.

A UUID is really just a 128 bit number, so I guess it would mostly work the same internally, aside from converting to a number first, and also needing to deal with big numbers.

UUIDs are ugly and long in URLs, and when using UUIDv1 you end up with lots that have the same suffix (MAC address).  And the middle parts (date) are pretty similar too.  

The more compact and varied output from hashids would be awesome for URLs and user-facing UUIDs.

# Current maximum input?

On a related note, I haven't been able to find a documented highest number that JS hashids accepts as input? I guess maybe it's dependent on the JS versions etc being used, so there's no fixed number in the library itself?  

I've spent quite a bit of time playing around with https://codepen.io/ivanakimov/pen/bNmExm including entering numbers like 2^63, 2^127, 2^128 (but as the full calculated long numbers) ... and sometimes it appears to work (gives output) - but the output looks too short, and the displayed $("#input") is empty.

So it seems sometimes it is actually failing to work properly, but not throwing an exception?  Maybe this is a limitation on JS itself and you can't detect invalid input?  I don't know enough JS to know if it's possible for you to detect bad input and throw exceptions?

If there's already a way to pass 128 bit numbers into hashids somehow (or some other representation like binary), please let me know.

Thanks!

**Comment by grantcarthew** [comment]
Two months ago I was looking at hashids to do exactly this. Great suggestion @hi2u. I ended up just using UUIDs in my URLs. Could easily switch to using a hash id. This feature would be popular.

This is open source though and this package does exactly what @ivanakimov wants it to do. I don't have the time to work on this. If you do @hi2u I would be grateful. If @ivanakimov does, even better.

**Comment by ivanakimov** [comment]
JavaScript's biggest number is `Number.MAX_SAFE_INTEGER` which is `2^53 - 1`. If the number is too big, you can always split it up and pass as multiple numbers to `hashids.encode`.

To encode UUIDs:
```javascript
const hashids = new Hashids();

const id = hashids.encodeHex('1b671a64-40d5-491e-99b0-da01ff1f3341'.replace(/-/g, ''));
const uuid = hashids.decodeHex(id);
```

**Comment by christiaanwesterbeek** [comment]
Just a little addition to what @ivanakimov wrote when you want to build the uuid with dashes as it was before encoding.

```javascript
hashids.decodeHex(id)
  .replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})/, (m1, m2, m3, m4, m5, m6) =>
    `${m2}-${m3}-${m4}-${m5}-${m6}`)
```
