### ISSUE TITLE
Using for react-native

### ISSUE THREAD

**Issue by alien3d** [ivanakimov/hashids.js#43]
I just remove the **.babelrc** and it work..  I'm not sure how to suggest to patch.  

```

var Hashids = require('hashids');
var userHash = new Hashids(your_hash);
console.log(userHash.encode("test"))

```

I try to use the  import but failed.. but as long it work using old require.. okay

**Comment by j-f1** [comment]
Try using `import * as Hashids from 'hashids'`.

**Comment by alien3d** [comment]
thanks will try ..

**Comment by threesquared** [comment]
I was having some problems with RN, I had to add `babel-plugin-transform-es2015-modules-umd` `babel-preset-es2015` and `babel-plugin-add-module-exports` to my devDependencies to be able to bundle the app JS for release.

**Comment by ivanakimov** [comment]
Please reopen if still an issue.

**Comment by Luktm** [comment]
> Please reopen if still an issue.

I was having issue with the RN. The problem was if I declared it as 'new Hashids()'. It shows error on 'Object is not a constructor(evaluating 'new Hashieds(......)'.


```
import * as Hashids from 'hashids';
const hashids = new Hashids('this is my salt');

componentWillMount() {
   console.log(hashids.encode(1));
}

```

![screenshot_1543246928](https://user-images.githubusercontent.com/24861458/49025077-d9405480-f1d5-11e8-9372-60519bfb6348.png)

**Comment by ilin-in** [comment]
Just use `import { default as Hashids } from 'hashids';`

**Comment by brentonhouse** [comment]
It's not just react native that this messes up.  There needs to be a proper module.exports so everyone doesn't have to use babel and plugins to be able to use.

**Comment by j-f1** [comment]
@brentonhouse try `require('hashids/cjs')`.
