### ISSUE TITLE
limited lottery characters for length 4

### ISSUE THREAD

**Issue by peonmodel** [ivanakimov/hashids.js#44]
when the minLength === 4, regardless of salt value, the selection for lottery characters is limited to 4 characters

the problem doesnt occur when minlength is 8 or 3 or none

```
hashids = new Hashids('stuff', 4);
dict={}
for (let ii =0;ii<200;++ii){
if (!dict[hashids.encode(ii)[0]]) { dict[hashids.encode(ii)[0]] = true }
}
dict  // {0: true, 8: true, g: true, p: true}

hashids = new Hashids('stuf333f',4);  // different salt
dict={}
for (let ii =0;ii<200;++ii){
if (!dict[hashids.encode(ii,ii+1)[0]]) { dict[hashids.encode(ii)[0]] = true }
}
dict // {6: true, J: true, n: true, R: true}
```

**Comment by ivanakimov** [comment]
Hah, good find :) Looks like maths do not work out properly for 4. Plus need a bit more randomization. Unfortunately not much I can do at this point as libs are all synced up, but I'll keep this in mind for next major release. Thank you.
