### ISSUE TITLE
predictable seps characters

### ISSUE THREAD

**Issue by peonmodel** [ivanakimov/hashids.js#45]
if the length of seps is too short, the algorithms simply uses the first few characters of the given alphabet to pad seps

i.e.
alphabet = 'bdgjklmnpqrvwxyzBDGJKLMNPQRVWXYZ1234567890'
since there is no overlap with the default seps characters, seps is now ''
seps will now be taken from the first few characters ''bdgjklmnpqr'

however, as the alphabet had not been shuffled, the seps are predictable

to fix this, the alphabet should be shuffle immediately after checking for validity of the alphabet, i.e.
line 
```
this.alphabet = this._shuffle(this.alphabet, this.salt);
```
should be right after 
```
if (this.alphabet.indexOf(' ') !== -1) {
  throw new Error('error: alphabet cannot contain spaces');
}
```

**Comment by ivanakimov** [comment]
Yes, there's a few things to improve, but because all libraries generate the same ids, this would have to wait till next major release. Thanks for feedback.
