### ISSUE TITLE
QUESTION: is there a way to find out why a decode failed?

### ISSUE THREAD

**Issue by Tawpie** [ivanakimov/hashids.js#46]
48hBNARK5jWmr5TW9VlkJmw decodes fine

but 6XsPA29JMKW432Ah5yQB5Ej6 fails.

Both are generated (JS) from an array of 3 ints, the last being a timestamp. (I don't have the exact source ints... sorry)

**Comment by ivanakimov** [comment]
Can't say without an example. Feel free to dm me your salt.
Otherwise, check obvious things -- like case-sensitivity in ids.
