### ISSUE TITLE
Compatibility with hashid libraries in other languages

### ISSUE THREAD

**Issue by oyeanuj** [ivanakimov/hashids.js#47]
Hi @ivanakimov, apologies for n00b question. I was hoping to use `hashids` on both server (Rails-API) and client (Javascript). I am fairly new to hashing and I wasn't sure if I would get reliably consistent results on both server-side and client-side when encoding/decoding the hashids. Should that be the case?

Thank you!

**Comment by manigandham** [comment]
Yes, as listed on the main site under "compatibility", all the different libraries should work fine with each other as long as they are the same version, and you're using the same salt value.

http://hashids.org/#compatibility

Javascript only supports numbers up to `2^53 - 1` though so if you're going to use 64-bit integers than you need to split them up or handle them some other way for the client/js side.

**Comment by ivanakimov** [comment]
Yes, should be compatible, if not please open an issue in either repo w/ examples.
