### ISSUE TITLE
[Suggestion] Make anti-curse algorithm optional

### ISSUE THREAD

**Issue by Frondor** [ivanakimov/hashids.js#48]
Since current anti-curse algorithm can't deal with languages other than english, can we make it optional?
i.e., `new Hashids('', 0, 'abcdefghijklmnopqrstuvwxyz', false)` (pass `false` for disabling these checks,  backward compatible with the current api).

[OFF-TOPIC]
Now, besides of that, I have some questions I want to address here instead of creating new issues.

 1. If I pass a reduced alphabet, am I incrementing the collision chances? If so, does incrementing the padding or providing a longer salt mitigates that issue? I personally think that removing some letters is a better "anti-curses" algorithm because it may require less CPU and isn't bound to a single language.
 2. I did some jsperf for encoding and decoding, and found out that encoding process is not really cheap, but decoding is quite fast. So if I am hashing ids on-the-fly for a large collection of items I just pulled from a db query, that's going to add a lot of overhead to the request. So I'm saving the generated hash along with the record (on a non-indexed column), so I have to encode only at insert time, and then I decode on the fly so the db queries still make use of the autoincrementing id (index).
Now... reading this https://github.com/ivanakimov/hashids.php/issues/22 its suggested to use a `case-sensitive` collation for that table, which is not possible for my case since I'm using a full-text index on the same table. So I was thinking on removing all the lowercase letters from the provided alphabet, now it gets me to the previous question again... Any advice or suggestion?

**Comment by ivanakimov** [comment]
Custom separators are already a feature request in https://github.com/ivanakimov/hashids.js/issues/17

1. With any kind of alphabet you should not encounter id collisions from the same constructor.
2. Not sure what your actual issue is -- the case-sensitive suggestion is to notify users that ids are case-sensitive by default. If you have all lowercase or uppercase in your alphabet, you don't have to worry about it at db-level then.
