### ISSUE TITLE
Looks like first 5 characters of the alphabet aren't used at all

### ISSUE THREAD

**Issue by dsamoylov** [ivanakimov/hashids.js#52]
I've played around with the lib a bit and noticed that first 5 characters of the alphabet aren't used.

For example
> `var hashids = new Hashids("SomeSalt", 9, "bvgwd*1234567890");`

only `*` and digits used in id being computed.

**Comment by ivanakimov** [comment]
That depends on your "salt", and the "salt" does not work like a true hash -- if you change one character it does not guarantee that your ids will be completely different.
