### ISSUE TITLE
Crash bug v 1.2.0

### ISSUE THREAD

**Issue by hempels** [ivanakimov/hashids.js#54]
I'm not sure what details are relevant, but our node.js app crashes immediately on startup following upgrade to version 1.2.0 of hashids. The crash is resolved by reverting to version 1.1.4. The only error message is as follows:

```
hashids\dist\hashids.js:4
Object.defineProperty(Hashids, "__esModule", {value: true});
       ^

TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (native)
    at Object.<anonymous> (...\node_modules\hashids\dist\hashids.js:4:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
```

**Comment by clem-witii** [comment]
I've come across the same issue as well. I'm running with node v8.11.4 and use `require('hasids')` to import the hashids in. I've been able to repeat this error on a PC and Ubuntu.

**Comment by niieani** [comment]
Sorry about this, I've tested it manually, plus in browser scenarios... I'm not sure how I managed to skip this change, but it seems it must have slipped in. Added a fix in the PR.

**Comment by ivanakimov** [comment]
@niieani thanks, merged.
@hempels @clem-witii does it fix the issue?

**Comment by hempels** [comment]
> @hempels @clem-witii does it fix the issue?

Release 1.2.2 fixes the issue for us. Thank you.

**Comment by ivanakimov** [comment]
@niieani any chance you could ping me at ivan@barreleye.com ?
