### ISSUE TITLE
Use .npmignore to publish only production-necessary files

### ISSUE THREAD

**Issue by ryanblock** [ivanakimov/hashids.js#61]
Hi! We dig your project and use it quite a bit.

Noticed recently you're not using `.npmignore`, and are publishing a lot of extra files to the production module, including test dirs, bower config, etc.

Would you be amenable to a PR that resolves this?

Additionally if so, do you have any feelings about that also ignoring unnecessary files from `dist`?

Thanks!

**Comment by ivanakimov** [comment]
Sure, optimizations are welcome. Please make sure it doesn't break anything for client/server.

**Comment by ryanblock** [comment]
Low hanging fruit is easy, anything in specific you feel ought to be distributed (or not) in `dist`?
